name: Deploy Vulnerable Application                                  # workflow name
#Test
on:
  push:
    branches:
      - master
jobs:
  deploy-heroku:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gentile-gonzalo" #Must be unique in Heroku
          heroku_email: "gonza.gentile@gmail.com"
          branch: "master"
          usedocker: true
